version: "3.9"

services:
  # server:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend/:/backend/
  #   command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - 8000:8000

  mariadb:
    image: mariadb
    container_name: mariadb
    env_file:
      - ./backend/.env
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
