version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
